### ISSUE TITLE
unable to load metric: jenkins.job.completed

### ISSUE THREAD

**Issue by kylezengTR** [DataDog/jenkins-datadog-plugin#131]
Hi Team, 
I found this problem which occurs on our server when using jenkins datadog:
In the server which has datadog agent installed, we are able to find the metric:
![image](https://user-images.githubusercontent.com/9773049/48491617-93ef5080-e7ed-11e8-9c57-31798e5fa499.png)

In the server which has no datadog agent installed, we are not able to find '**completed**' metric but something else:
![image](https://user-images.githubusercontent.com/9773049/48491678-b5503c80-e7ed-11e8-82a3-d768adc46841.png)
Also, when integrating this jenkins server to datadog, we have to paste the jenkins host to the _jenkins integration page_, so the datadog will receive the jenkins events:
![image](https://user-images.githubusercontent.com/9773049/48492320-217f7000-e7ef-11e8-8b83-02f60f78350d.png)

Please let me know if you need more details, thanks.

**Comment by sjenriquez** [comment]
Hi @kylezengTR. The Datadog agent is needed to collect the `jenkins.job.completed` metric because it uses the statsd collector in the agent, see this repo's readme for a full description of the available metrics.

For the second issue you're seeing, can you open a ticket via support@datadoghq.com, we can better assist via our support channel. Thanks!
