### ISSUE TITLE
Use DataDog Application Key instead of just the API Key

### ISSUE THREAD

**Issue by jmellor** [DataDog/jenkins-datadog-plugin#36]
Currently it is not possible to isolate data from Jenkins to a Jenkins application key in DataDog, creating a lot of noise for other applications being monitored in DataDog.  It would be useful to configure and use  the application key to isolate this traffic.

**Comment by JohnLZeller** [comment]
Hey @jmellor, thanks for the ticket! Application keys in DataDog are not actually used to isolate traffic, but to authenticate certain actions. So that I understand correctly, are you looking to be able to filter your monitors based on the type of Jenkins job, or host? If this is the case, filtering is done by tags, and for this integration there is currently a host tag you can use to filter out specific Jenkins hosts, as well as tags pertaining to `result` and `job`. Please let me know if this answers your needs.
