### ISSUE TITLE
Multiple DataDog Accounts per Jenkins

### ISSUE THREAD

**Issue by muhqu** [DataDog/jenkins-datadog-plugin#80]
We're using a shared Jenkins Server/Cluster and like to have the ability to integrate with different DataDog Accounts on a per job basis. Can this plugin also be configured on a per job basis?

**Comment by sjenriquez** [comment]
Hey @muhqu, thanks for the ticket! Currently it isn't possible to report to multiple Datadog accounts. Adding additional tags is the only per job configuration at this time. This sounds like a useful enhancement. We'll explore this in a future release, if you start work on this in the meantime, feel free to open a PR, thanks!

**Comment by gzussa** [comment]
Since release 1.0.0, users can use dogstatsd to submit metrics, events and service checks to Datadog. It is possible to configure the Datadog Agent to submit metrics to multiple accounts. 
Using such feature may increase your cost. Please contact our support to get more details on how to set this up.
