### ISSUE TITLE
Pull API key from credential store

### ISSUE THREAD

**Issue by neybar** [DataDog/jenkins-datadog-plugin#93]
This is a 'nice to have' feature, but I would like to be able to use the [Credentials Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin) to pull my datadog API key from.

In Manage Jenkins -> Configure System -> Datadog -> API Key I would like to see either a form field, or a drop down to use a stored credential.

**Comment by sjenriquez** [comment]
Hi @neybar, we've talked about adding support for the Credentials Plugin. We'll add in a future release.

**Comment by gzussa** [comment]
Since release 1.0.0, the datadog plugin can submit metrics, events and service checks using DogStatsD. Using DogStatsD allows you to hide your keys from Jenkins. We are not planning to integrate our plugin with the `Credentials` plugin at the moment. However, we are welcoming pull requests from the community to add such feature.

**Comment by gzussa** [comment]
Me again 😄. We are in the process of kill this repo i n favor of https://github.com/jenkinsci/datadog-plugin. As a consequence, I am closing this issue. Feel free to open a new one in https://github.com/jenkinsci/datadog-plugin/issues in order to get community help on this. Even better, we welcome pull requests 💯
